project_id = "cthfacthzfdfeehjwsvl"

[functions.send-candidate-email]
verify_jwt = false

[functions.hubspot-contact]
verify_jwt = false

[functions.hubspot-candidate]
verify_jwt = false

[functions.hubspot-duediligence]
verify_jwt = false

[functions.alba-chat]
verify_jwt = false